const homes = [{
  bedroom1: "bedroom 1",
  bedroom2: "bedroom 2",
  bedroom3: undefined,
  bathroom1: "bathroom",
  bathroom2: undefined,
  bathroom3: undefined,
  kitchen: "kitchen",
  dining: "dining room",
  living: "living room",
  basement: undefined,
  attic: undefined,
  roof: undefined,
  tasks: [
    {
      area: "bedroom1",
      taskName: "taskName___469",
      taskDescription: "description 469",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___1122",
      taskDescription: "description 1122",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1133",
      taskDescription: "description 1133",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1227",
      taskDescription: "description 1227",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___269",
      taskDescription: "description 269",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___433",
      taskDescription: "description 433",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___881",
      taskDescription: "description 881",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___517",
      taskDescription: "description 517",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___264",
      taskDescription: "description 264",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___820",
      taskDescription: "description 820",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1225",
      taskDescription: "description 1225",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___14",
      taskDescription: "description 14",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1210",
      taskDescription: "description 1210",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___926",
      taskDescription: "description 926",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___416",
      taskDescription: "description 416",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___537",
      taskDescription: "description 537",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___234",
      taskDescription: "description 234",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___1031",
      taskDescription: "description 1031",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___921",
      taskDescription: "description 921",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1145",
      taskDescription: "description 1145",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___879",
      taskDescription: "description 879",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___297",
      taskDescription: "description 297",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___41",
      taskDescription: "description 41",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___222",
      taskDescription: "description 222",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___371",
      taskDescription: "description 371",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___916",
      taskDescription: "description 916",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___438",
      taskDescription: "description 438",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___388",
      taskDescription: "description 388",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___1075",
      taskDescription: "description 1075",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___325",
      taskDescription: "description 325",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___477",
      taskDescription: "description 477",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___547",
      taskDescription: "description 547",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1149",
      taskDescription: "description 1149",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___615",
      taskDescription: "description 615",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___24",
      taskDescription: "description 24",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___147",
      taskDescription: "description 147",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___632",
      taskDescription: "description 632",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___1111",
      taskDescription: "description 1111",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___973",
      taskDescription: "description 973",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1198",
      taskDescription: "description 1198",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___746",
      taskDescription: "description 746",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___24",
      taskDescription: "description 24",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___374",
      taskDescription: "description 374",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1130",
      taskDescription: "description 1130",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1003",
      taskDescription: "description 1003",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___771",
      taskDescription: "description 771",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___196",
      taskDescription: "description 196",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1040",
      taskDescription: "description 1040",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___545",
      taskDescription: "description 545",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___759",
      taskDescription: "description 759",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___220",
      taskDescription: "description 220",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___252",
      taskDescription: "description 252",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___57",
      taskDescription: "description 57",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___1083",
      taskDescription: "description 1083",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___880",
      taskDescription: "description 880",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1005",
      taskDescription: "description 1005",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___969",
      taskDescription: "description 969",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___680",
      taskDescription: "description 680",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1151",
      taskDescription: "description 1151",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___33",
      taskDescription: "description 33",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___570",
      taskDescription: "description 570",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___548",
      taskDescription: "description 548",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___2",
      taskDescription: "description 2",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___48",
      taskDescription: "description 48",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___176",
      taskDescription: "description 176",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___389",
      taskDescription: "description 389",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___19",
      taskDescription: "description 19",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___737",
      taskDescription: "description 737",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___156",
      taskDescription: "description 156",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___957",
      taskDescription: "description 957",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1073",
      taskDescription: "description 1073",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___170",
      taskDescription: "description 170",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___525",
      taskDescription: "description 525",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___847",
      taskDescription: "description 847",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1179",
      taskDescription: "description 1179",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1056",
      taskDescription: "description 1056",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___290",
      taskDescription: "description 290",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___348",
      taskDescription: "description 348",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___922",
      taskDescription: "description 922",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1054",
      taskDescription: "description 1054",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___671",
      taskDescription: "description 671",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___539",
      taskDescription: "description 539",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___425",
      taskDescription: "description 425",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1166",
      taskDescription: "description 1166",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1026",
      taskDescription: "description 1026",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___210",
      taskDescription: "description 210",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___330",
      taskDescription: "description 330",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___29",
      taskDescription: "description 29",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___226",
      taskDescription: "description 226",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___137",
      taskDescription: "description 137",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1031",
      taskDescription: "description 1031",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___553",
      taskDescription: "description 553",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___883",
      taskDescription: "description 883",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___762",
      taskDescription: "description 762",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___285",
      taskDescription: "description 285",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1170",
      taskDescription: "description 1170",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___868",
      taskDescription: "description 868",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___222",
      taskDescription: "description 222",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___767",
      taskDescription: "description 767",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1121",
      taskDescription: "description 1121",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___496",
      taskDescription: "description 496",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___687",
      taskDescription: "description 687",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1216",
      taskDescription: "description 1216",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___194",
      taskDescription: "description 194",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1024",
      taskDescription: "description 1024",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___1233",
      taskDescription: "description 1233",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1120",
      taskDescription: "description 1120",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___21",
      taskDescription: "description 21",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___445",
      taskDescription: "description 445",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___544",
      taskDescription: "description 544",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___455",
      taskDescription: "description 455",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___861",
      taskDescription: "description 861",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___9",
      taskDescription: "description 9",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___864",
      taskDescription: "description 864",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___370",
      taskDescription: "description 370",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___401",
      taskDescription: "description 401",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___916",
      taskDescription: "description 916",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___123",
      taskDescription: "description 123",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___177",
      taskDescription: "description 177",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___151",
      taskDescription: "description 151",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___705",
      taskDescription: "description 705",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___401",
      taskDescription: "description 401",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1020",
      taskDescription: "description 1020",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___242",
      taskDescription: "description 242",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___359",
      taskDescription: "description 359",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___65",
      taskDescription: "description 65",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1078",
      taskDescription: "description 1078",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___110",
      taskDescription: "description 110",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___219",
      taskDescription: "description 219",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___241",
      taskDescription: "description 241",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___884",
      taskDescription: "description 884",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___77",
      taskDescription: "description 77",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1032",
      taskDescription: "description 1032",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___638",
      taskDescription: "description 638",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___122",
      taskDescription: "description 122",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___800",
      taskDescription: "description 800",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___1094",
      taskDescription: "description 1094",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___653",
      taskDescription: "description 653",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___185",
      taskDescription: "description 185",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1012",
      taskDescription: "description 1012",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___650",
      taskDescription: "description 650",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___262",
      taskDescription: "description 262",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___858",
      taskDescription: "description 858",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___195",
      taskDescription: "description 195",
      taskStatus: false,
      costEstimate: undefined,
    },
  ],
},
{
  bedroom1: "bedroom 1",
  bedroom2: undefined,
  bedroom3: undefined,
  bathroom1: "bathroom",
  bathroom2: undefined,
  bathroom3: undefined,
  kitchen: "kitchen",
  dining: undefined,
  living: undefined,
  basement: undefined,
  attic: undefined,
  roof: undefined,
  tasks: [
    {
      area: "bedroom1",
      taskName: "taskName___469",
      taskDescription: "description 469",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___1122",
      taskDescription: "description 1122",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1133",
      taskDescription: "description 1133",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1227",
      taskDescription: "description 1227",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___269",
      taskDescription: "description 269",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___433",
      taskDescription: "description 433",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___881",
      taskDescription: "description 881",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___517",
      taskDescription: "description 517",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___264",
      taskDescription: "description 264",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___820",
      taskDescription: "description 820",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1225",
      taskDescription: "description 1225",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___14",
      taskDescription: "description 14",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1210",
      taskDescription: "description 1210",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___926",
      taskDescription: "description 926",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___416",
      taskDescription: "description 416",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___537",
      taskDescription: "description 537",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___234",
      taskDescription: "description 234",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___1031",
      taskDescription: "description 1031",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___921",
      taskDescription: "description 921",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1145",
      taskDescription: "description 1145",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___879",
      taskDescription: "description 879",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___297",
      taskDescription: "description 297",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___41",
      taskDescription: "description 41",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___222",
      taskDescription: "description 222",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___371",
      taskDescription: "description 371",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___916",
      taskDescription: "description 916",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___438",
      taskDescription: "description 438",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___388",
      taskDescription: "description 388",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___1075",
      taskDescription: "description 1075",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___325",
      taskDescription: "description 325",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___477",
      taskDescription: "description 477",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___547",
      taskDescription: "description 547",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1149",
      taskDescription: "description 1149",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___615",
      taskDescription: "description 615",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___24",
      taskDescription: "description 24",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___147",
      taskDescription: "description 147",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___632",
      taskDescription: "description 632",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___1111",
      taskDescription: "description 1111",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___973",
      taskDescription: "description 973",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1198",
      taskDescription: "description 1198",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___746",
      taskDescription: "description 746",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___24",
      taskDescription: "description 24",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___374",
      taskDescription: "description 374",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1130",
      taskDescription: "description 1130",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1003",
      taskDescription: "description 1003",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___771",
      taskDescription: "description 771",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___196",
      taskDescription: "description 196",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1040",
      taskDescription: "description 1040",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___545",
      taskDescription: "description 545",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___759",
      taskDescription: "description 759",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___220",
      taskDescription: "description 220",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___252",
      taskDescription: "description 252",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___57",
      taskDescription: "description 57",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___1083",
      taskDescription: "description 1083",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___880",
      taskDescription: "description 880",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1005",
      taskDescription: "description 1005",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___969",
      taskDescription: "description 969",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___680",
      taskDescription: "description 680",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1151",
      taskDescription: "description 1151",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___33",
      taskDescription: "description 33",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___570",
      taskDescription: "description 570",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___548",
      taskDescription: "description 548",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___2",
      taskDescription: "description 2",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___48",
      taskDescription: "description 48",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___176",
      taskDescription: "description 176",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___389",
      taskDescription: "description 389",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___19",
      taskDescription: "description 19",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___737",
      taskDescription: "description 737",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___156",
      taskDescription: "description 156",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___957",
      taskDescription: "description 957",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1073",
      taskDescription: "description 1073",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___170",
      taskDescription: "description 170",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___525",
      taskDescription: "description 525",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___847",
      taskDescription: "description 847",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1179",
      taskDescription: "description 1179",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1056",
      taskDescription: "description 1056",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___290",
      taskDescription: "description 290",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___348",
      taskDescription: "description 348",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___922",
      taskDescription: "description 922",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1054",
      taskDescription: "description 1054",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___671",
      taskDescription: "description 671",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___539",
      taskDescription: "description 539",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___425",
      taskDescription: "description 425",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1166",
      taskDescription: "description 1166",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1026",
      taskDescription: "description 1026",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___210",
      taskDescription: "description 210",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___330",
      taskDescription: "description 330",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___29",
      taskDescription: "description 29",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___226",
      taskDescription: "description 226",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___137",
      taskDescription: "description 137",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1031",
      taskDescription: "description 1031",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___553",
      taskDescription: "description 553",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___883",
      taskDescription: "description 883",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___762",
      taskDescription: "description 762",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___285",
      taskDescription: "description 285",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___1170",
      taskDescription: "description 1170",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___868",
      taskDescription: "description 868",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___222",
      taskDescription: "description 222",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___767",
      taskDescription: "description 767",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___1121",
      taskDescription: "description 1121",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___496",
      taskDescription: "description 496",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___687",
      taskDescription: "description 687",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1216",
      taskDescription: "description 1216",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___194",
      taskDescription: "description 194",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___1024",
      taskDescription: "description 1024",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___1233",
      taskDescription: "description 1233",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___1120",
      taskDescription: "description 1120",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___21",
      taskDescription: "description 21",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___445",
      taskDescription: "description 445",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___544",
      taskDescription: "description 544",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___455",
      taskDescription: "description 455",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___861",
      taskDescription: "description 861",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___9",
      taskDescription: "description 9",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___864",
      taskDescription: "description 864",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___370",
      taskDescription: "description 370",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___401",
      taskDescription: "description 401",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___916",
      taskDescription: "description 916",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___123",
      taskDescription: "description 123",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___177",
      taskDescription: "description 177",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___151",
      taskDescription: "description 151",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___705",
      taskDescription: "description 705",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___401",
      taskDescription: "description 401",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___1020",
      taskDescription: "description 1020",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___242",
      taskDescription: "description 242",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___359",
      taskDescription: "description 359",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___65",
      taskDescription: "description 65",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___1078",
      taskDescription: "description 1078",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___110",
      taskDescription: "description 110",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___219",
      taskDescription: "description 219",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___241",
      taskDescription: "description 241",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___884",
      taskDescription: "description 884",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___77",
      taskDescription: "description 77",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom1",
      taskName: "taskName___1032",
      taskDescription: "description 1032",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom2",
      taskName: "taskName___638",
      taskDescription: "description 638",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bedroom3",
      taskName: "taskName___122",
      taskDescription: "description 122",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom1",
      taskName: "taskName___800",
      taskDescription: "description 800",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom2",
      taskName: "taskName___1094",
      taskDescription: "description 1094",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "bathroom3",
      taskName: "taskName___653",
      taskDescription: "description 653",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "kitchen",
      taskName: "taskName___185",
      taskDescription: "description 185",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "dining",
      taskName: "taskName___1012",
      taskDescription: "description 1012",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "living",
      taskName: "taskName___650",
      taskDescription: "description 650",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "basement",
      taskName: "taskName___262",
      taskDescription: "description 262",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "attic",
      taskName: "taskName___858",
      taskDescription: "description 858",
      taskStatus: false,
      costEstimate: undefined,
    },
    {
      area: "roof",
      taskName: "taskName___195",
      taskDescription: "description 195",
      taskStatus: false,
      costEstimate: undefined,
    },
  ],
}]

exports.module = homes;